### DISCUSSION TITLE
Celery is not responsive when the worker is running a task

### DISCUSSION THREAD

**Discussion by saeedesmaili** [celery/celery#7241] [Q&A]
I'm using Celery with FastAPI to run some background tasks when an endpoint is being called. I also have another endpoint to ask Celery about the status and the result of a specific task.

The problem occurs when the worker is running a task, and I want to get the status of that specific task or even another already finished task. Celery doesn't respond in the `get_task_status` function, and the request remains in the loading state, until the worker finishes running the other task. Then, it reacts to `get_task_status` and returns the status in milliseconds. But if the worker is idle, it responds to 'get_task_status' immediately.

Is this the normal behaviour, or am I missing something? How can I get the status of the tasks that are currently running or have been finished a while ago, without waiting for the worker to be idle?
 

```python
## celery_worker.py
...
celery = Celery(__name__)
celery.conf.broker_url = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379")
celery.conf.result_backend = os.environ.get("CELERY_RESULT_BACKEND", "redis://localhost:6379")

@celery.task(name="create_example_task")
def create_example_task():
    result = do_long_running_task(duration="1min")
    return result
...
```

```python
## fastapi endpoints to run a task and to get the status of the task
## main.py
...
from fastapi import APIRouter
from celery.result import AsyncResult
from celery_worker import create_example_task

app = FastAPI()

@app.post("/", status_code=201)
def run_task():
    task = create_example_task.delay()
    output = {"task_id": task.id}
    return output


@app.get("/{task_id}")
def get_task_status(task_id: str):
    task = AsyncResult(task_id)
    output = {
        "id": task_id,
        "status": task.status,
        "result": task.result
    }
    return output
```

```yaml
# docker-compose.yml
...
  worker:
    build: ./src
    command: celery --app=celery_worker.celery worker --beat --concurrency=4 --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./src:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
...
```
