### DISCUSSION TITLE
celery flower logs are not clearing

### DISCUSSION THREAD

**Discussion by harshdeep-techstax** [celery/celery#8837] [Q&A]
I have enabled result_expires with  10 value for 10 seconds for testing and have enabled celery beat by -B flag in celery and flower it is run in a docker container have the following config in docker-compose.yml.
After doing all this the flower logs are not clearing up and consuming a lot of RAM as it accumulates. Is there any other way to clear the flower logs ?
```
  celery:
      container_name: celery
      build: "jobs/"
      env_file:
        - "jobs/.env"
      command: "celery -A app.tasks.celery worker -B --loglevel=info"
      user: nobody
      volumes:
          - "./jobs:/usr/src/app"
      depends_on:
        - db
      networks:
        - "rabbitmq"

  flower:
    container_name: flower
    build: "jobs/"
    env_file:
      - "jobs/.env"
    command: "celery flower -A worker -B --app=app.tasks.celery --loglevel=info --url_prefix=flower --address=0.0.0.0 --port=5555"
    user: nobody
    ports:
      - 5555:5555
    volumes:
        - "./jobs:/usr/src/app"
    networks:
      - "rabbitmq"
```
