### DISCUSSION TITLE
Tasks received from RedBeat but not execute

### DISCUSSION THREAD

**Discussion by phucnb** [celery/celery#8865] [Q&A]
If an celery-worker has about 10-15 tasks, then it stops processing new tasks from RedBeatScheduler which are created dynamically during work. But it will processing after a while sometime 1 minute but sometimes up to 30 minutes.
 However, if there are less than 10 tasks, then they start working instantly and the worker successfully accepts them. 
Restarting processes doesn't help but if the number of task reduce then it's back to normal.
try -p eventlet and gevent but still not work.

```
version: '3'

services:
  redis:
    image: redis
    volumes:
        - redis_data5:/data

  web:
    build:
      context: .
    environment:
      TZ: America/New_York  # Set the timezone for the web service
      FLASK_APP: run
      FLASK_DEBUG: 1
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0
    ports:
      - "127.0.0.1:5000:5000"

  celery:
    build:
        context: .
    environment:
      TZ: America/New_York  # Set the timezone for the celery service
      FLASK_APP: run
    volumes:
      - .:/app
    command: /bin/sh -c "pip install eventlet && celery -A run.celery worker --loglevel=info -P eventlet"
    depends_on:
      - redis

  beat:
    build:
        context: .
    environment:
      TZ: America/New_York  # Set the timezone for the beat service
      FLASK_APP: run
    volumes:
      - .:/app
    command: celery -A run.celery beat -S redbeat.RedBeatScheduler --max-interval 10 --loglevel=info
    depends_on:
      - celery
  flower:
    build:
        context: .
    environment:
      FLASK_APP: run
    volumes:
      - .:/app
    command: celery -A run.celery flower --loglevel=info
    ports:
      -  "127.0.0.1:5555:5555"
    depends_on:
      - celery
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      TZ: America/New_York  # Set the timezone for the redis-commander service
      REDIS_HOSTS: local:redis:6379
    ports:
      - "127.0.0.1:8081:8081"

volumes:
    redis_data5:
```
