### DISCUSSION TITLE
non-intuitive results with x-max-priority value for celery priority queues

### DISCUSSION THREAD

**Discussion by SamComber** [celery/celery#9415] [General]
I'm trying to implement priority queues in celery and have noticed strange things.

Here are my queues and setup...

```
from kombu import Exchange, Queue

broker_url = 'amqp://user:password@localhost:5672//'

worker_prefetch_multiplier = 1
task_acks_late = True

# Priority Queues
GENERATE_MESSAGES = "generate_messages"
SUGGEST_REPLIES = "suggest_replies"
INSTANT_REPLIES = "instant_replies"
SUMMARISE_CONVERSATIONS = "summarise_conversations"
SUMMARISE_CALLS = "summarise_calls"

task_queues = (
    Queue(
        GENERATE_MESSAGES,
        Exchange(GENERATE_MESSAGES),
        routing_key=GENERATE_MESSAGES,
        queue_arguments={"x-max-priority": 0},
    ),
    Queue(
        SUGGEST_REPLIES,
        Exchange(SUGGEST_REPLIES),
        routing_key=SUGGEST_REPLIES,
        queue_arguments={"x-max-priority": 127},
    ),
    Queue(
        SUMMARISE_CALLS,
        Exchange(SUMMARISE_CALLS),
        routing_key=SUMMARISE_CALLS,
        queue_arguments={"x-max-priority": 255},
    ),
)

```

This is a figure tracking task start and end times (apologies for the length).

![image](https://github.com/user-attachments/assets/a814bf74-10b6-49fd-9bff-be3439ef2b12)

Can anyone explain this behaviour? It is counter to documentation here https://www.rabbitmq.com/docs/priority#resource-usage indicating higher value translates to a higher priority, but you can see clearly the `message_generation` task has the lowest x-max-priority and are prioritised before any task in the above.

Deploy is:

```
version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  celery_workers:
    deploy:
      replicas: 3
    build: .
    command: celery -A app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//
```
