### ISSUE TITLE
Documentation issue: BROKER_URL !== CELERY_BROKER_URL

### ISSUE THREAD

**Issue by chris-hydra** [celery/celery#3187]
Thanks for all the great work on Celery - cross-posting this in case anyone else has this issue using Celery in Docker.

The documentation doesn't make it clear that `BROKER_URL` is deprecated in favour of `CELERY_BROKER_URL`.

The [configuration](http://docs.celeryproject.org/en/latest/configuration.html) documentation makes no mention of `CELERY_BROKER_URL` - all examples use `BROKER_URL`.

If you use the [official Celery image](https://github.com/docker-library/celery) in a docker-compose setup and rename your RabbitMQ service to anything but "rabbit" in your `docker-compose.yml`, and try (according to the  [configuration docs](http://docs.celeryproject.org/en/latest/configuration.html)) to set `BROKER_URL` accordingly, this image won't work.

For example, this docker-compose file won't work:

```
foo:
  image: rabbitmq:3
  expose:
    - "5672"

celery:
  image: celery:3.1
  environment:
    - BROKER_URL=amqp://guest:guest@foo//
  links:
    - foo
```

`[ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@rabbit:5672//: [Errno -2] Name or service not known.`

This works:

```
foo:
  image: rabbitmq:3
  expose:
    - "5672"

celery:
  image: celery:3.1
  environment:
    - CELERY_BROKER_URL=amqp://guest:guest@foo//
  links:
    - foo
```
