### ISSUE TITLE
Unstable group workflow feature. 

### ISSUE THREAD

**Issue by ehengao** [celery/celery#4925]
## Checklist

software -> celery:4.2.0 (windowlicker) kombu:4.2.1 py:3.6.3
            billiard:3.5.0.4 py-amqp:2.3.2
platform -> system:Linux arch:64bit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:amqp results:redis://127.0.0.1:6379/

BROKER_URL: 'amqp://guest:********@127.0.0.1:5672//'
CELERY_ACCEPT_CONTENT: ['json']
CELERY_RESULT_BACKEND: 'redis://127.0.0.1:6379/'
CELERY_RESULT_SERIALIZER: 'json'
CELERY_TASK_PROTOCOL: 2
CELERY_TASK_SERIALIZER: 'json'
os: <module 'os' from '/home/ehengao/miniconda3/envs/nia-dcs/lib/python3.6/os.py'>
CELERY_INCLUDE: ['nia_dcs.ccwp.tasks']

- [ ] I have verified that the issue exists against the `master` branch of Celery.
yes

## Steps to reproduce
Run following test

def test_add_with_group():
    """test add task from the tutorial as a group
    """
    for i in range(100):
        print(f'Runnint test {i}')
        add1 = add.s(1, 2)
        add2 = add.s(3, 4)
        g = group(add1, add2)()
        print(f'GroupTasks:{g} sent!')
        r = g.get()
        print(r)

## Expected behavior
Task would pass every time. (randomly not always happen)

## Actual behavior
Task some time blocked and causing pytest in continues integration never returns. After doing some digging into the celery code. noticed that things randomly happen when the AsyncResult.__del__ triggered somehow to delete RedisBacken._pending_result before the result is adding to the ResultConsumer.buckets causing the GroupResult still waiting for one of the task to finish.

**Comment by cp2587** [comment]
Hello,
we witnessed the same issue on our side. We had to re-implement polling in order to have a consistent behavior.

```
while not async_res.ready():
            sleep(interval)
            if timeout and time() - start > timeout:
                raise TimeoutError
return async_res.get(propagate=propagate)
```

Any news on this issue ? On version 3.X we never had any issue of this kind.

**Comment by bakcsa83** [comment]
I'm experiencing the same issue. https://github.com/celery/celery/issues/5040
`async_res.get(propagate=propagate)` indeed helps, but that is just a nasty workaround.

**Comment by greuff** [comment]
Unfortunately we seem to be experiencing the same issue with 4.2.1. Is there a previous version of Celery that is known to work?

**Comment by jerr0328** [comment]
Saw this as well, although it's certainly more like a race condition where we couldn't reliably reproduce it locally. We did have see it sometimes using a docker-compose file (slightly modified since we have separate worker and requestor nodes) that looks something like:

```yaml
version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.6-alpine
        ports:
            - "5672"
        networks:
            - messaging

    redis:
        image: redis:3-alpine
        ports:
            - "6379"
        networks:
            - messaging

    uut:
        image: <your testing image>
        depends_on:
            - rabbitmq
            - redis
        networks:
            - messaging
        environment:
            - CELERY_BROKER=amqp://guest:guest@rabbitmq:5672
            - CELERY_RESULT_BACKEND=redis://redis:6379/0

networks:
    messaging:
```

(Fill in the unit under test (uut) image above, or change it to build a Docker image). Larger executions, e.g. with 10 tasks taking ~5-10s each, was pretty reliably reproducing the problem, so hopefully that can be helpful for reproducing the bug.
