### ISSUE TITLE
Migrate CI from travis & AppVeyor to Github-Actions

### ISSUE THREAD

**Issue by auvipy** [celery/celery#5543]
1. - Unit
    - Integration
    - lint
reasoning behind this : Proposed code changes need to pass the unit test to be accepted as valid changes. Than the integration test to verify the changes with whole system. The last stage will verify code quality and lint issues. IMHO triggering lint as first stage is quite annoying for the contributors as it stop the unit & integration stage which is annoying.

**Comment by georgepsarakis** [comment]
@auvipy I think this is a better approach and can lead to a faster feedback loop for contributors. It will also make Pull Request review easier, as tests will not be blocked by linter failures.

I would like to make another suggestion though, we could also define [stages](https://github.com/celery/celery/blob/6d2a8652e1bb3723f3acfc7d3a8891913d6ad22c/.travis.yml#L12) that will include one unit & one integration test, for faster error checking:

```yaml
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
os:
    - linux
stages:
  - unit-test-python-latest
  - integration-rabbimq
  - unit-test-python-other-versions
  - integration-other-brokers
  - lint
env:
  global:
  - PYTHONUNBUFFERED=yes

matrix:
  include:
  - python: 3.7
    env: MATRIX_TOXENV=integration-rabbitmq
    stage: integration-rabbitmq
  - python: 3.7
    env: MATRIX_TOXENV=unit
    stage: unit-test-python-latest
```
