### ISSUE TITLE
Parameterize integration test Dockerfile by Python version

### ISSUE THREAD

**Issue by remeika** [celery/celery#5814]
# Checklist

* [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical enhancement to an existing feature.
* [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Issue+Type%3A+Enhancement%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed enhancements.
* [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the if the same enhancement was already implemented in the
  master branch.
* [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

#### Related Issues
* None

#### Possible Duplicates
* None

# Brief Summary
Currently, integration tests are run in a single [Docker container](https://github.com/celery/celery/blob/master/docker/Dockerfile) where all supported Python versions are installed and managed by pyenv. This creates the following issues:

* Running integration tests against a single version of Python is slower than necessary, because unneeded  python versions and corresponding requirements must be installed.
* We cannot take advantage of the [official python containers](https://hub.docker.com/_/python) which also adds unnecessary run time because we install download and install python  before each test run
* Pyenv is needed to manage the multiple python versions living in one container. This solution obviously works well 

I propose we parameterize the integration test dockerfile by python version.

# Design
Use the dockerfile [`ARG` ](https://docs.docker.com/engine/reference/builder/#arg) feature to parameterize the integration test docker file. Then in the docker compose file define an image for each python version:

```
services:
  celery27:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        CELERY_USER: developer
        PYTHON_VERSION: 2.7
    ...
  celery34:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        CELERY_USER: developer
        PYTHON_VERSION: 3.4
    ...
```

## Architectural Considerations

None

## Proposed Behavior
Ultimately, instead of running this line to execute integration tests on 2.7:

```
docker-compose run --rm celery pyenv exec python2.7 -m pytest t/integration
```

We'd run this

```
docker-compose run --rm celery27 pytest t/integration
```

## Diagrams

N/A

## Alternatives

None
